CREATE SEQUENCE SEQ_MEMBER;
DROP TABLE TBL_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(1000) UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(1000) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(1000) NOT NULL,
	RECOMMANDER_ID VARCHAR2(1000)
);

INSERT INTO TBL_MEMBER
(ID, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS)
VALUES(SEQ_MEMBER.NEXTVAL, 'hds1234', '1234', '한동석', '경기도 남양주시');
INSERT INTO TBL_MEMBER
(ID, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS, RECOMMANDER_ID)
VALUES(SEQ_MEMBER.NEXTVAL, 'asd1234', '1234', '한동석', '경기도 남양주시', 'hds1234');
INSERT INTO TBL_MEMBER
(ID, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS, RECOMMANDER_ID)
VALUES(SEQ_MEMBER.NEXTVAL, 'zxc1234', '1234', '한동석', '경기도 남양주시', 'asd1234');
INSERT INTO TBL_MEMBER
(ID, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS, RECOMMANDER_ID)
VALUES(SEQ_MEMBER.NEXTVAL, 'qwe1234', '1234', '한동석', '경기도 남양주시', 'qwe1234');
INSERT INTO TBL_MEMBER
(ID, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS, RECOMMANDER_ID)
VALUES(SEQ_MEMBER.NEXTVAL, 'fgh1234', '1234', '한동석', '경기도 남양주시', 'fgh1234');

SELECT * FROM TBL_MEMBER;

SELECT COUNT(MEMBER_ID) FROM TBL_MEMBER
GROUP BY RECOMMANDER_ID
HAVING RECOMMANDER_ID = '?'

SELECT MEMBER_ID FROM TBL_MEMBER WHERE RECOMMANDER_ID = ?;
SELECT RECOMMANDER_ID FROM TBL_MEMBER WHERE MEMBER_ID = ?;