CREATE SEQUENCE SEQ_REPLY;

DROP TABLE TBL_REPLY;
CREATE TABLE TBL_REPLY(
   ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
   REPLY_CONTENT VARCHAR2(1000) NOT NULL,
   POST_ID NUMBER NOT NULL,
   MEMBER_ID NUMBER NOT NULL,
   CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
   REFERENCES TBL_POST(ID),
   CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID)
);

SELECT * FROM TBL_REPLY;

INSERT INTO TBL_REPLY
(ID, REPLY_CONTENT , POST_ID, MEMBER_ID)
VALUES(SEQ_REPLY.NEXTVAL, '댓글 내용1', 63, 21);

